user_login_and_register-master/project/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth

from .router import router
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    ######### api path ##########################

    path('api/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name='api-tokn-auth'),

    #####user related path##########################
    path('', include('user.urls')),

    path('Login/', user_view.Login, name='Login'),
    path('logout/', auth.LogoutView.as_view(template_name='user/login.html'), name='logout'),
    path('register/', user_view.register, name='register'),
    path('actionUrl/', user_view.actionUrl, name='actionUrl'),
    path('my_form/', user_view.my_form, name='my_form'),
    path('maindishes/', user_view.maindishes, name='maindishes'),
    path('RecipePagee/<int:pk>', user_view.RecipePagee, name='RecipePagee'),
    path('neww/', user_view.neww, name='neww'),
    path('Starters/', user_view.Starters, name='Starters'),
    path('Salads/', user_view.Salads, name='Salads'),
    path('Desserts/', user_view.Desserts, name='Desserts'),
    path('EmailSend/', user_view.EmailSend, name='EmailSend'),
    path('My_Recipe/', user_view.My_Recipe, name='My_Recipe'),
    path('my_form_edit/<int:pk>', user_view.my_form_edit, name='my_form_edit'),
    path('update/<int:pk>', user_view.update, name='update'),
    path('delete/<int:pk>', user_view.delete, name='delete'),
    path('NewIndex/', user_view.NewIndex, name='NewIndex'),
    path('NewIndex2/', user_view.NewIndex2, name='NewIndex2'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_login_and_register-master/user/urls.py
from django.urls import path, include
from django.conf import settings
from . import views

from django.conf.urls.static import static

urlpatterns = [
         path('', views.NewIndex2, name='NewIndex2'),

]

user_login_and_register-master/user/models.py
from django.contrib.auth.models import User
from django.db import models
from jsonfield import JSONField


class Recipe(models.Model):
    author = models.CharField(max_length=24, unique=False, default='Main dishes')
    fullname = models.CharField(max_length=20)
    Time = models.IntegerField()
    choices = [
        ('Easy', 'Easy'),
        ('Normal', "Normal"),
        ('Hard', "Hard")
    ]
    categories = [
        ('Starters', 'Starters'),
        ('Salads', "Salads"),
        ('Main dishes', "Main dishes"),
        ('Desserts', "Desserts"),
    ]
    Difficulty = models.CharField(max_length=24, choices=choices, default='Easy', unique=False)
    categoriesss = models.CharField(max_length=24, choices=categories, default='Main dishes')

    ResText = models.TextField()
    Ingredients = models.TextField()
    upload = models.ImageField(upload_to='media/uploads', null=False, blank=False)















class Review(models.Model):
    name = models.CharField(max_length=24, unique=False, default='Name')
    date = models.CharField(max_length=24)
    Text = models.TextField()

user_login_and_register-master/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from user.models import Recipe, Review


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length=20)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ['username', 'email', 'phone_no', 'password1', 'password2']


class MyForm(forms.ModelForm):
    class Meta:
        model = Recipe

        fields = ["fullname", "Time", "Difficulty","categoriesss", "ResText", "Ingredients","upload","author"]
        labels = {'fullname': "Name", "Time": "Time to Cook", "Difficulty": "Difficulty", "ResText": "Instructions"
            , "Ingredients": "Ingredients","categoriesss":"Categories","upload":"upload","author":"author"}


class MyForm2(forms.ModelForm):
    class Meta:
        model = Review

        fields = ["name", "date", "Text"]
        labels = {'name': "name", "date": "date", "Text": "Text"}

user_login_and_register-master/user/views.py
import string
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.http import HttpResponseRedirect, HttpResponse
import user
from .forms import UserRegisterForm, MyForm, MyForm2
from django.conf import settings
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.urls import reverse
##################################################################
####################index#######################################
from .models import Recipe
from django.shortcuts import render
from qrcode import *
from django.utils.dateparse import parse_datetime

languageVer='Hebrew'

def index(request):
    return render(request, 'user/index.html', {'title': 'index'})


def NewIndex(request):
    global languageVer
    languageVer=request.POST.get('author')
    return render(request, 'user/NewIndex.html', {'title': 'index' ,'author':request.POST.get('author')})

def NewIndex2(request):
    return render(request, 'user/lag.html')

########################################################################
########### register here #####################################
@csrf_exempt
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST) or None
        if form.is_valid():
            username = request.POST.get('username')
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Profile details updated.')

            return render(request, 'user/login.html' ,{'languageVer':languageVer})
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form': form, 'title': 'reqister here','author':request.POST.get('author'),'usernameDef':request.POST.get('username'),'emailDef':request.POST.get('email')})


###################################################################################
################login forms###################################################

def Login(request):
    if request.method == 'POST':

        # AuthenticationForm_can_also_be_used__
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' wecome {username} !!')
            return redirect('neww')
        else:
            messages.info(request, f'account does not exit plz sign in')
    form = AuthenticationForm()
    return render(request, 'user/login.html', {'form': form, 'title': 'log in' ,'languageVer':languageVer })


def actionUrl(request):
    return render(request, 'user/NewCv-form.html')


def neww(request):
    mainn = Recipe.objects.all()
    return render(request, 'user/neww.html', {'mainn': mainn ,'languageVer':languageVer})

@csrf_exempt
def my_form(request):
    if request.method == "POST":
        labels2 = {'fullname': "Name", "Time": "Time to Cook", "Difficulty": "Difficulty", "ResText": "Instructions"
            , "Ingredients": "Ingredients","categoriesss":"Categories","upload":"upload","author":"author"}
        labels2['fullname']=request.POST['fullname']
        labels2['Time']=request.POST['Time']
        templist=list(request.POST)
        if 'Difficulty1' in templist:
             labels2['Difficulty']='Easy'
        if 'Difficulty2' in templist:
             labels2['Difficulty']='Normal'
        if 'Difficulty3' in templist:
             labels2['Difficulty']='Hard'
        labels2['ResText']=request.POST['ResText']
        labels2['Ingredients']=request.POST['Ingredients']
        labels2['categoriesss']=request.POST['categoriesss']
        labels2['author']=request.POST['author']
        form = MyForm(labels2,request.FILES)
        form.instance.rel_user = request.user
        if form.is_valid():
            form.save()
            return redirect('neww')

    else:
        form = MyForm()
    return render(request, 'user/cv-form.html' ,{'languageVer':languageVer})

@csrf_exempt
def my_form_edit(request, pk):
    x = Recipe.objects.filter(id=pk)
    return render(request, 'user/my_form_edit.html', {'x': x ,'languageVer':languageVer})


def maindishes(request):
    mainn = Recipe.objects.filter(categoriesss="Main dishes")
    img_name=""
    s = len(mainn.values())
    img_name_dic = []
    for i in range(s):
        data = "https://cooking.pythonanywhere.com/RecipePagee/" + str(mainn.values('id')[i]['id'])
        img = make(data)
        img_name = 'qr' + str(mainn.values('id')[i]['id']) + '.png'
        img_name_dic.append(img_name)
        print(img_name_dic)
        img.save(settings.MEDIA_ROOT + '/' + img_name)
    return render(request, 'user/Maindishes.html', {'mainn': mainn,"img_name_dic":img_name_dic ,'languageVer':languageVer},)


def Starters(request):
    mainn = Recipe.objects.filter(categoriesss="Starters")
    return render(request, 'user/Starters.html', {'mainn': mainn ,'languageVer':languageVer})


def Salads(request):
    mainn = Recipe.objects.filter(categoriesss="Salads")
    return render(request, 'user/Salads.html', {'mainn': mainn ,'languageVer':languageVer})


def Desserts(request):
    mainn = Recipe.objects.filter(categoriesss="Desserts")
    return render(request, 'user/Desserts.html', {'mainn': mainn ,'languageVer':languageVer})


def RecipePagee(request, pk):
    x = Recipe.objects.filter(id=pk)
    y = x.values('Ingredients')[0]['Ingredients']
    y2 = x.values('ResText')[0]['ResText']
    t2 = y2.split(".")
    t= y.split(".")
    from langdetect import detect
    language=detect(y2)
    return render(request, 'user/RecipePage.html', {'x': x,'t':t ,'t2':t2 ,'language':language})


def EmailSend(request):
    if request.method == "POST":
        labels3={}
        labels3['name']=request.POST['name']
        labels3['date']=request.POST['date']
        labels3['Text']=request.POST['Text']
        form2 = MyForm2(labels3)
        form2.instance.rel_user = request.user
        if form2.is_valid():
            print(form2)
            form2.save()
            return redirect('neww')
    else:
        form2 = MyForm2()
    return render(request, {'form2': form2})


def My_Recipe(request):
    x = Recipe.objects.filter(author=request.user)
    return render(request, 'user/My_Recipe.html', {'x': x ,'languageVer':languageVer})

@csrf_exempt
def update(request, pk):
    Recipe.objects.filter(id=pk).update(fullname=request.POST['fullname'], Time=request.POST['Time'],
                                        ResText=request.POST['ResText'], Ingredients=request.POST['Ingredients'])
    return render(request, 'user/neww.html' ,{'languageVer':languageVer})


def delete(request, pk):
    Recipe.objects.filter(id=pk).delete()
    return redirect('neww')

user_login_and_register-master/user/templates/user/Email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

user_login_and_register-master/user/templates/user/My_res.html
<style>
.btn-bgstroke {
  font-size: 20px;
  display: inline-block;
  border: 1px solid white;
  padding: 10px 20px;
  border-radius: 10px;
  cursor: pointer;
  font-weight: 300;
  margin-top: 30px;
position: fixed;
         bottom: -122;
        right: 6;
       z-index: 2;

}
.btn-bgstroke:hover {
  background-color: white;
  color: #33cccc;

}
html,
body {
  height: 100%;
}

body {
  margin: 0;
  background: linear-gradient(45deg, #49a09d, #5f2c82);
  font-family: sans-serif;
  font-weight: 100;
}

.container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

table {
  width: 800px;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}

th,
td {
  padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;
}

th {
  text-align: left;
}

thead
{
        th
        {
            background-color: #55608f;
        }
}

tbody {
  tr {
    &:hover {
      background-color: rgba(255,255,255,0.3);
    }
  }
  td {
    position: relative;
    &:hover {
      &:before {
        content: "";
        position: absolute;
        left: 0;
        right: 0;
        top: -9999px;
        bottom: -9999px;
        background-color: rgba(255,255,255,0.2);
        z-index: -1;
      }
    }
  }
}
</style>
<div class="container">

        <div class="container">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Time</th>
        <th>Difficulty</th>
        <th>Recipe Page</th>

      </tr>
    </thead>
    <tbody>
      {% for obj in mainn %}
      <tr>
        <td>{{ obj.fullname }}</td>
        <td>{{ obj.Time }}</td>
        <td>{{ obj.Difficulty }}</td>
              <form action="{% url 'RecipePagee' obj.id %}" method="post">
    {% csrf_token %}

            <input id="search" name="search" type="hidden" class="query-search"
            placeholder="Search..." value={{ obj.id}} >
         <td>   <input class="btn btn-primary" type="submit" value="Lets go"><td>

            </form>


        <td>



        </td>


      </tr>
    {% endfor %}

    </tbody>
  </table>
    </form>
     <form method="GET" action="/neww">
        <button class="btn-bgstroke">
                    Exit
                </button>
             </form>
    </tbody>
</div>

</div>

user_login_and_register-master/user/templates/user/QR.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

user_login_and_register-master/user/templates/user/cv-form.html
{% load static %}




<!DOCTYPE html>
<!-- saved from url=(0136)https://www.pythonanywhere.com/user/Cooking/files/home/Cooking/ResWeb/user_login_and_register-master/user/templates/user/NewCv-form.html -->
<html lang="en" dir="ltr"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins',sans-serif;
}
body{
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}
.container{
  max-width: 1500px;
  width: 500%;
  height:100%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.container .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.container .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}
.content form .user-details{
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  margin: 20px 0 12px 0;
}
form .user-details .input-box{
  margin-bottom: 15px;
  width: calc(100% / 2 - 20px);
}
form .input-box span.details{
  display: block;
  font-weight: 500;
  margin-bottom: 5px;
}
.user-details .input-box input{
  height: 45px;
  width: 100%;
  outline: none;
  font-size: 16px;
  border-radius: 5px;
  padding-left: 15px;
  border: 1px solid #ccc;
  border-bottom-width: 2px;
  transition: all 0.3s ease;
}
.user-details .input-box input:focus,
.user-details .input-box input:valid{
  border-color: #9b59b6;
}
 form .gender-details .gender-title{
  font-size: 20px;
  font-weight: 500;
 }
 form .category{
   display: flex;
   width: 80%;
   margin: 14px 0 ;
   justify-content: space-between;
 }
 form .category label{
   display: flex;
   align-items: center;
   cursor: pointer;
 }
 form .category label .dot{
  height: 18px;
  width: 18px;
  border-radius: 50%;
  margin-right: 10px;
  background: #d9d9d9;
  border: 5px solid transparent;
  transition: all 0.3s ease;
}
 #dot-1:checked ~ .category label .one,
 #dot-2:checked ~ .category label .two,
 #dot-3:checked ~ .category label .three
 {
   background: #9b59b6;
   border-color: #d9d9d9;
 }
 form input[type="radio"]{
   display: none;
 }
 form .button{
   height: 45px;
   margin: 35px 0
 }
 form .button input{
   height: 100%;
   width: 100%;
   border-radius: 5px;
   border: none;
   color: #fff;
   font-size: 18px;
   font-weight: 500;
   letter-spacing: 1px;
   cursor: pointer;
   transition: all 0.3s ease;
   background: linear-gradient(135deg, #71b7e6, #9b59b6);
 }
 form .button input:hover{
  /* transform: scale(0.99); */
  background: linear-gradient(-135deg, #71b7e6, #9b59b6);
  }
 @media(max-width: 584px){
 .container{
  max-width: 100%;
}
form .user-details .input-box{
    margin-bottom: 15px;
    width: 100%;
  }
  form .category{
    width: 100%;
  }
  .content form .user-details{
    max-height: 300px;
    overflow-y: scroll;
  }
  .user-details::-webkit-scrollbar{
    width: 5px;
  }
  }
  @media(max-width: 459px){
  .container .content .category{
    flex-direction: column;
  }
}






    </style>



{% if languageVer == 'English' %}

    <!---<title> Responsive Registration Form | CodingLab </title>--->
    <link rel="stylesheet" href="./NewCv-form_files/style.css">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body data-new-gr-c-s-check-loaded="14.1086.0" data-gr-ext-installed="">
  <div class="container">
    <div class="title">Recipe page</div>
    <div class="content">
      <form method="POST" enctype="multipart/form-data">
        <div class="user-details">
          <div class="input-box">
            <span class="details">Name</span>
            <input type="text" placeholder="Enter your name" name="fullname" required="">
          </div>
          <div class="input-box">
            <span class="details">Time to Cook</span>
            <input type="number" placeholder="Time to Cook" name="Time" required="">
          </div>
          <div class="input-box">
            <span class="details">Picture</span>
            <input type="file" placeholder="Enter your email" required="" name="upload">
          </div>
          <div class="input-box">
            <span class="details">Author</span>
            <input type="hidden" value=    {{ user.username }} required="" name="author" >
            <span class="details">{{ user.username }}</span>
          </div>
          <div class="input-box">
            <span class="details">Ingredients</span>
           <textarea name="Ingredients" cols="40" rows="10" required="" id="id_Ingredients"></textarea>
          </div>

          <div class="input-box">
            <span class="details">Instructions</span>
           <textarea name="ResText" cols="40" rows="10" required="" id="id_ResText"></textarea>
          </div>
        </div>
        <div class="gender-details">
          <input type="radio" name="Difficulty1" id="dot-1">
          <input type="radio" name="Difficulty2" id="dot-2">
          <input type="radio" name="Difficulty3" id="dot-3">
          <span class="gender-title">Difficulty</span>
          <div class="category">
            <label for="dot-1">
            <span class="dot one"></span>
            <span class="gender">Easy</span>
          </label>
          <label for="dot-2">
            <span class="dot two"></span>
            <span class="gender">Normal</span>
          </label>
            <label for="dot-3">
            <span class="dot three"></span>
            <span class="gender">Hard</span>
          </label>

          </div>
 </div>

 <p><label for="id_categoriesss">Categories:</label> <select name="categoriesss" id="id_categoriesss">
   <option value="Starters">Starters</option>

   <option value="Salads">Salads</option>

   <option value="Main dishes" selected>Main dishes</option>

   <option value="Desserts">Desserts</option>

 </select></p>
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
    </div>
  </div>
{% else %}


    <!---<title> Responsive Registration Form | CodingLab </title>--->
    <link rel="stylesheet" href="./NewCv-form_files/style.css">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body data-new-gr-c-s-check-loaded="14.1086.0" data-gr-ext-installed="">
  <div class="container">
    <div class="title">דף מתכון</div>
    <div class="content">
      <form method="POST" enctype="multipart/form-data">
        <div class="user-details">
          <div class="input-box">
            <span class="details "dir="rtl">שם</span>
            <input type="text" style="text-align: right" placeholder="הכנס את שם המתכון" name="fullname" required="">
          </div>
          <div class="input-box">
            <span class="details" dir="rtl">זמן הכנה</span>
            <input type="number" style="text-align: right" placeholder="זמן הכנה" name="Time" required="">
          </div>
          <div class="input-box">
            <span class="details" dir="rtl">תמונה</span>
            <input type="file" placeholder="העלה תמונה" required="" name="upload">
          </div>
          <div class="input-box">
            <span class="details">כותב</span>
            <input type="hidden" value=    {{ user.username }} required="" name="author" >
            <span class="details">{{ user.username }}</span>
          </div>
          <div class="input-box">
            <span class="details" dir="rtl">מצרכים</span>
           <textarea name="Ingredients" style="text-align: right" cols="107" rows="10" required="" id="id_Ingredients"></textarea>
          </div>

          <div class="input-box">
            <span class="details" dir="rtl">הוראות הכנה</span>
           <textarea name="ResText" style="text-align: right" cols="107" rows="10" required="" id="id_ResText"></textarea>
          </div>
        </div>
        <div class="gender-details">
          <input type="radio" name="Difficulty1" id="dot-1">
          <input type="radio" name="Difficulty2" id="dot-2">
          <input type="radio" name="Difficulty3" id="dot-3">
          <span class="gender-title">קושי</span>
          <div class="category">
            <label for="dot-1">
            <span class="dot one"></span>
            <span class="gender">קל</span>
          </label>
          <label for="dot-2">
            <span class="dot two"></span>
            <span class="gender">בנוני</span>
          </label>
            <label for="dot-3">
            <span class="dot three"></span>
            <span class="gender">קשה</span>
          </label>

          </div>
 </div>

 <p><label for="id_categoriesss">קטגוריה:</label> <select name="categoriesss" id="id_categoriesss">
   <option value="Starters">מנות פתיחה</option>

   <option value="Salads">סלטים</option>

   <option value="Main dishes" selected>עקריות</option>

   <option value="Desserts">קינוחים</option>

 </select></p>
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
    </div>
  </div>


































{% endif  %}


</body><grammarly-desktop-integration data-grammarly-shadow-root="true"></grammarly-desktop-integration></html>

user_login_and_register-master/user/templates/user/lag.html
<!DOCTYPE html>
<html lang="">

	<style>
* {
	 box-sizing: border-box;
	 margin: 0;
	 padding: 0;
}
 body {
	 width: 100%;
	 height: 100vh;
	 display: flex;
	 overflow: hidden;
}
 .btn-container {
	 width: 100%;
	 height: 100%;
	 display: flex;
	 justify-content: center;
	 align-items: center;
	 background: var(--bg);
}
 .btn-container:nth-child(1) {
	 --btn-bg: #00a7da;
	 --bg: #ffffff;
}
 .btn-container:nth-child(2) {
	 --btn-bg: #fac300;
	 --bg: #828282;
;
}
 button {
	 --width: 180px;
	 --height: 60px;
	 border: 0;
	 position: relative;
	 min-width: var(--width);
	 min-height: var(--height);
	 border-radius: var(--height);
	 color: #fff;
	 font-family: "Montserrat";
	 font-weight: bold;
	 background: rgba(0, 0, 0, 0.3);
	 cursor: pointer;
	 overflow: hidden;
	 display: flex;
	 justify-content: center;
	 align-items: center;
	 margin: 0 1rem;
}
 button .text, button .icon-container {
	 position: relative;
	 z-index: 2;
}
 button .icon-container {
	 --icon-size: 25px;
	 position: relative;
	 width: var(--icon-size);
	 height: var(--icon-size);
	 margin-left: 15px;
	 transition: transform 500ms ease;
}
 button .icon-container .icon {
	 position: absolute;
	 left: 0;
	 top: 0;
	 width: var(--icon-size);
	 height: var(--icon-size);
	 transition: transform 500ms ease, opacity 250ms ease;
}
 button .icon-container .icon--left {
	 transform: translateX(-200%);
	 opacity: 0;
}
 button .icon-container .icon svg {
	 width: 100%;
	 height: 100%;
	 fill: #fff;
}
 button::after {
	 content: "";
	 position: absolute;
	 left: 0;
	 top: 0;
	 width: 100%;
	 height: 100%;
	 background: var(--btn-bg);
	 border-radius: var(--height);
	 z-index: 1;
	 transition: transform 500ms ease;
}
 button:hover::after {
	 transform: translateX(65%);
}
 button:hover .icon-container {
	 transform: translateX(125%);
}
 button:hover .icon-container .icon--left {
	 transform: translateX(0);
	 opacity: 1;
}
 button:hover .icon-container .icon--right {
	 transform: translateX(200%);
	 opacity: 0;
}
 .support {
	 position: absolute;
	 right: 10px;
	 bottom: 10px;
	 padding: 10px;
	 display: flex;
}
 .support a {
	 margin: 0 10px;
	 color: #fff;
	 font-size: 1.8rem;
	 backface-visibility: hidden;
	 transition: all 150ms ease;
}
 .support a:hover {
	 transform: scale(1.1);
}

    </style>

<div class="btn-container">
    <form action="{% url "NewIndex" %}" method="POST">
                        {% csrf_token %}
	<button>
		<span class="text">English</span>
		<div class="icon-container">
			<div class="icon icon--left">
				<svg>
					<use xlink:href="#arrow-right"></use>
				</svg>
			</div>
			<div class="icon icon--right">
				<svg>
					<use xlink:href="#arrow-right"></use>
				</svg>
			</div>
		</div>

		    <p><input type="hidden" name="author" value="English" maxlength="24" required id="id_author"></p>
	</button>
        </form>

</div>

<div class="btn-container">
    <form action="{% url "NewIndex" %}" method="POST">
                        {% csrf_token %}
	<button>
		<span class="text">עברית</span>
		<div class="icon-container">
			<div class="icon icon--left">
				<svg>
					<use xlink:href="#arrow-right"></use>
				</svg>
			</div>
			<div class="icon icon--right">
				<svg>
					<use xlink:href="#arrow-right"></use>
				</svg>
			</div>
		</div>
				    <p><input type="hidden" name="author" value="Hebrew" maxlength="24" required id="id_author"></p>

	</button>
	        </form>

</div>

<svg style="display: none;">
	<symbol id="arrow-right" viewBox="0 0 20 10">
		<path d="M14.84 0l-1.08 1.06 3.3 3.2H0v1.49h17.05l-3.3 3.2L14.84 10 20 5l-5.16-5z"></path>
	</symbol>
</svg>

<div class="support">
	<a href="https://twitter.com/DevLoop01" target="_blank"><i class="fab fa-twitter-square"></i></a>
	<a href="https://dribbble.com/devloop01" target="_blank"><i class="fab fa-dribbble"></i></a>
</div>



</html>